name: release_tag_on_development_branch

on:
  push:
    tags:
      - 'release-*'

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo "Current branch = ${{github.event.base_ref}}"